language: java
sudo: true

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"

cache:
  directories:
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"

jobs:
  fast_finish: true
  jdk: openjdk11
  script:
    - "./gradlew build"

