language: java
sudo: false

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"

cache:
  directories:
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"

script: "mvn clean package"
